# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3477ec5659c92f6dc77404b2efec89400d5ef4806b5b9c4cd53c2506cd84698ddff3341ff88df1853190139605c578053b9053524412255df83c08bc890dc95

test:
  secret_key_base: 2dc698e727214a5460a2ea405067745971709b8d4c15df77526bef4de0154610092412af5118606df348139552067ce72a08d188dd2b1fb731d90d44caa6e8ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
